// Route Links
export const USER_PROFILE_LINK = '/';
export const ABOUT_LINK = '/about';
export const USER_REPOS_LINK = '/users/:username';

// User profile constants
export const GET_USER_PROFILE_PENDING = 'GET_USER_PROFILE_PENDING';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILURE = 'GET_USER_PROFILE_FAILURE';

// User repos constants
export const GET_USER_REPOS_PENDING = 'GET_USER_REPOS_PENDING';
export const GET_USER_REPOS_SUCCESS = 'GET_USER_REPOS_SUCCESS';
export const GET_USER_REPOS_FAILURE = 'GET_USER_REPOS_FAILURE';

export const FILTER_REPOS_BY_NAME = 'FILTER_REPOS_BY_NAME';
export const FILTER_REPOS_BY_NAME_INVALIDATE =
  'FILTER_REPOS_BY_NAME_INVALIDATE';
export const SORT_REPOS_BY_STARGAZERS_COUNT_ASC =
  'SORT_REPOS_BY_STARGAZERS_COUNT_ASC';
export const SORT_REPOS_BY_STARGAZERS_COUNT_DESC =
  'SORT_REPOS_BY_STARGAZERS_COUNT_DESC';
